export const registryAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "testnetMode_", type: "bool" },
      { name: "minStemLength_", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "registerChallenge",
    stateMutability: "view",
    inputs: [
      { name: "name", type: "string" },
      { name: "dekPublic", type: "bytes" },
      { name: "wrappedDek", type: "bytes" },
    ],
    outputs: [{ name: "", type: "bytes" }],
  },
  {
    type: "function",
    name: "optInChallenge",
    stateMutability: "view",
    inputs: [
      { name: "name", type: "string" },
      { name: "nodeKey", type: "bytes32" },
    ],
    outputs: [{ name: "", type: "bytes" }],
  },
  {
    type: "function",
    name: "nameRecord",
    stateMutability: "view",
    inputs: [{ name: "name", type: "string" }],
    outputs: [
      { name: "qx", type: "bytes32" },
      { name: "qy", type: "bytes32" },
      { name: "dekPublic", type: "bytes" },
      { name: "wrappedDek", type: "bytes" },
    ],
  },
  {
    type: "function",
    name: "isOptedIn",
    stateMutability: "view",
    inputs: [
      { name: "name", type: "string" },
      { name: "nodeKey", type: "bytes32" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "register",
    stateMutability: "nonpayable",
    inputs: [
      { name: "name", type: "string" },
      { name: "qx", type: "bytes32" },
      { name: "qy", type: "bytes32" },
      { name: "dekPublic", type: "bytes" },
      { name: "wrappedDek", type: "bytes" },
      {
        name: "auth",
        type: "tuple",
        components: [
          { name: "r", type: "bytes32" },
          { name: "s", type: "bytes32" },
          { name: "challengeIndex", type: "uint256" },
          { name: "typeIndex", type: "uint256" },
          { name: "authenticatorData", type: "bytes" },
          { name: "clientDataJSON", type: "string" },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "owner",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "admin",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "setAdmin",
    stateMutability: "nonpayable",
    inputs: [{ name: "admin_", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "registerNode",
    stateMutability: "nonpayable",
    inputs: [
      { name: "domain", type: "string" },
      { name: "masterKey", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "nodeOf",
    stateMutability: "view",
    inputs: [{ name: "masterKey", type: "bytes32" }],
    outputs: [{ name: "domain", type: "string" }],
  },
  {
    type: "function",
    name: "optIn",
    stateMutability: "nonpayable",
    inputs: [
      { name: "name", type: "string" },
      { name: "nodeKey", type: "bytes32" },
      {
        name: "auth",
        type: "tuple",
        components: [
          { name: "r", type: "bytes32" },
          { name: "s", type: "bytes32" },
          { name: "challengeIndex", type: "uint256" },
          { name: "typeIndex", type: "uint256" },
          { name: "authenticatorData", type: "bytes" },
          { name: "clientDataJSON", type: "string" },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "optOutChallenge",
    stateMutability: "view",
    inputs: [
      { name: "name", type: "string" },
      { name: "nodeKey", type: "bytes32" },
    ],
    outputs: [{ name: "", type: "bytes" }],
  },
  {
    type: "function",
    name: "optOut",
    stateMutability: "nonpayable",
    inputs: [
      { name: "name", type: "string" },
      { name: "nodeKey", type: "bytes32" },
      {
        name: "auth",
        type: "tuple",
        components: [
          { name: "r", type: "bytes32" },
          { name: "s", type: "bytes32" },
          { name: "challengeIndex", type: "uint256" },
          { name: "typeIndex", type: "uint256" },
          { name: "authenticatorData", type: "bytes" },
          { name: "clientDataJSON", type: "string" },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "optedOutAt",
    stateMutability: "view",
    inputs: [
      { name: "name", type: "string" },
      { name: "nodeKey", type: "bytes32" },
    ],
    outputs: [{ name: "", type: "uint64" }],
  },
  { type: "error", name: "DottedName", inputs: [] },
  { type: "error", name: "MissingTestnetSuffix", inputs: [] },
  { type: "error", name: "StemTooShort", inputs: [] },
  { type: "error", name: "ZeroMinStem", inputs: [] },
  { type: "error", name: "EmptyName", inputs: [] },
  { type: "error", name: "NameTaken", inputs: [] },
  { type: "error", name: "InvalidPasskey", inputs: [] },
  { type: "error", name: "InvalidDekPublic", inputs: [] },
  { type: "error", name: "UnknownName", inputs: [] },
  { type: "error", name: "UnknownNode", inputs: [] },
  { type: "error", name: "ZeroNodeKey", inputs: [] },
  { type: "error", name: "NotOwner", inputs: [] },
  { type: "error", name: "NotAdmin", inputs: [] },
  { type: "error", name: "EmptyDomain", inputs: [] },
  { type: "error", name: "NodeAlreadyRegistered", inputs: [] },
  { type: "error", name: "DomainTaken", inputs: [] },
] as const;
