export const registryAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "testnetMode_", type: "bool" },
      { name: "minStemLength_", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "registerChallenge",
    stateMutability: "view",
    inputs: [
      { name: "name", type: "string" },
      { name: "dekPublic", type: "bytes" },
      { name: "wrappedDek", type: "bytes" },
    ],
    outputs: [{ name: "", type: "bytes" }],
  },
  {
    type: "function",
    name: "optInChallenge",
    stateMutability: "view",
    inputs: [
      { name: "name", type: "string" },
      { name: "nodeKey", type: "bytes32" },
    ],
    outputs: [{ name: "", type: "bytes" }],
  },
  {
    type: "function",
    name: "nameRecord",
    stateMutability: "view",
    inputs: [{ name: "name", type: "string" }],
    outputs: [
      { name: "qx", type: "bytes32" },
      { name: "qy", type: "bytes32" },
      { name: "dekPublic", type: "bytes" },
      { name: "wrappedDek", type: "bytes" },
    ],
  },
  {
    type: "function",
    name: "isOptedIn",
    stateMutability: "view",
    inputs: [
      { name: "name", type: "string" },
      { name: "nodeKey", type: "bytes32" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "mailboxGeneration",
    stateMutability: "view",
    inputs: [{ name: "name", type: "string" }],
    outputs: [{ name: "", type: "uint64" }],
  },
  {
    type: "function",
    name: "nameExists",
    stateMutability: "view",
    inputs: [{ name: "name", type: "string" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "setEnsBridge",
    stateMutability: "nonpayable",
    inputs: [
      { name: "ensClaim_", type: "address" },
      { name: "crossDomainMessenger_", type: "address" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "register",
    stateMutability: "nonpayable",
    inputs: [
      { name: "name", type: "string" },
      { name: "qx", type: "bytes32" },
      { name: "qy", type: "bytes32" },
      { name: "dekPublic", type: "bytes" },
      { name: "wrappedDek", type: "bytes" },
      {
        name: "auth",
        type: "tuple",
        components: [
          { name: "r", type: "bytes32" },
          { name: "s", type: "bytes32" },
          { name: "challengeIndex", type: "uint256" },
          { name: "typeIndex", type: "uint256" },
          { name: "authenticatorData", type: "bytes" },
          { name: "clientDataJSON", type: "string" },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "owner",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "registerNode",
    stateMutability: "nonpayable",
    inputs: [
      { name: "domain", type: "string" },
      { name: "masterKey", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "nodeOf",
    stateMutability: "view",
    inputs: [{ name: "masterKey", type: "bytes32" }],
    outputs: [{ name: "domain", type: "string" }],
  },
  {
    type: "function",
    name: "optIn",
    stateMutability: "nonpayable",
    inputs: [
      { name: "name", type: "string" },
      { name: "nodeKey", type: "bytes32" },
      {
        name: "auth",
        type: "tuple",
        components: [
          { name: "r", type: "bytes32" },
          { name: "s", type: "bytes32" },
          { name: "challengeIndex", type: "uint256" },
          { name: "typeIndex", type: "uint256" },
          { name: "authenticatorData", type: "bytes" },
          { name: "clientDataJSON", type: "string" },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "optOutChallenge",
    stateMutability: "view",
    inputs: [
      { name: "name", type: "string" },
      { name: "nodeKey", type: "bytes32" },
    ],
    outputs: [{ name: "", type: "bytes" }],
  },
  {
    type: "function",
    name: "optOut",
    stateMutability: "nonpayable",
    inputs: [
      { name: "name", type: "string" },
      { name: "nodeKey", type: "bytes32" },
      {
        name: "auth",
        type: "tuple",
        components: [
          { name: "r", type: "bytes32" },
          { name: "s", type: "bytes32" },
          { name: "challengeIndex", type: "uint256" },
          { name: "typeIndex", type: "uint256" },
          { name: "authenticatorData", type: "bytes" },
          { name: "clientDataJSON", type: "string" },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "linkNodeChallenge",
    stateMutability: "view",
    inputs: [
      { name: "name", type: "string" },
      { name: "nodeKey", type: "bytes32" },
      { name: "newQx", type: "bytes32" },
      { name: "newQy", type: "bytes32" },
      { name: "inviteId", type: "bytes32" },
    ],
    outputs: [{ name: "", type: "bytes" }],
  },
  {
    type: "function",
    name: "linkNode",
    stateMutability: "nonpayable",
    inputs: [
      { name: "name", type: "string" },
      { name: "nodeKey", type: "bytes32" },
      { name: "newQx", type: "bytes32" },
      { name: "newQy", type: "bytes32" },
      { name: "inviteId", type: "bytes32" },
      {
        name: "auth",
        type: "tuple",
        components: [
          { name: "r", type: "bytes32" },
          { name: "s", type: "bytes32" },
          { name: "challengeIndex", type: "uint256" },
          { name: "typeIndex", type: "uint256" },
          { name: "authenticatorData", type: "bytes" },
          { name: "clientDataJSON", type: "string" },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "removeControllerChallenge",
    stateMutability: "view",
    inputs: [
      { name: "name", type: "string" },
      { name: "qx", type: "bytes32" },
      { name: "qy", type: "bytes32" },
    ],
    outputs: [{ name: "", type: "bytes" }],
  },
  {
    type: "function",
    name: "removeController",
    stateMutability: "nonpayable",
    inputs: [
      { name: "name", type: "string" },
      { name: "qx", type: "bytes32" },
      { name: "qy", type: "bytes32" },
      {
        name: "auth",
        type: "tuple",
        components: [
          { name: "r", type: "bytes32" },
          { name: "s", type: "bytes32" },
          { name: "challengeIndex", type: "uint256" },
          { name: "typeIndex", type: "uint256" },
          { name: "authenticatorData", type: "bytes" },
          { name: "clientDataJSON", type: "string" },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "inviteUsed",
    stateMutability: "view",
    inputs: [{ name: "inviteId", type: "bytes32" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "controllers",
    stateMutability: "view",
    inputs: [{ name: "name", type: "string" }],
    outputs: [
      { name: "qxList", type: "bytes32[]" },
      { name: "qyList", type: "bytes32[]" },
    ],
  },
  {
    type: "function",
    name: "optedOutAt",
    stateMutability: "view",
    inputs: [
      { name: "name", type: "string" },
      { name: "nodeKey", type: "bytes32" },
    ],
    outputs: [{ name: "", type: "uint64" }],
  },
  { type: "error", name: "DottedName", inputs: [] },
  { type: "error", name: "MissingTestnetSuffix", inputs: [] },
  { type: "error", name: "StemTooShort", inputs: [] },
  { type: "error", name: "ZeroMinStem", inputs: [] },
  { type: "error", name: "EmptyName", inputs: [] },
  { type: "error", name: "NameTaken", inputs: [] },
  { type: "error", name: "InvalidPasskey", inputs: [] },
  { type: "error", name: "InvalidDekPublic", inputs: [] },
  { type: "error", name: "UnknownName", inputs: [] },
  { type: "error", name: "UnknownNode", inputs: [] },
  { type: "error", name: "ZeroNodeKey", inputs: [] },
  { type: "error", name: "OwnableUnauthorizedAccount", inputs: [{ name: "account", type: "address" }] },
  { type: "error", name: "OwnableInvalidOwner", inputs: [{ name: "owner", type: "address" }] },
  { type: "error", name: "EmptyDomain", inputs: [] },
  { type: "error", name: "NodeAlreadyRegistered", inputs: [] },
  { type: "error", name: "DomainTaken", inputs: [] },
  { type: "error", name: "InviteUsed", inputs: [] },
  { type: "error", name: "ZeroInviteId", inputs: [] },
  { type: "error", name: "ControllerExists", inputs: [] },
  { type: "error", name: "TooManyControllers", inputs: [] },
  { type: "error", name: "UnknownController", inputs: [] },
  { type: "error", name: "LastController", inputs: [] },
] as const;
