FROM node:22-bookworm-slim
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --omit=dev
COPY client ./client
COPY relayer ./relayer
COPY node ./node
COPY dal ./dal
ENV NODE_ENV=production
EXPOSE 8080
CMD ["node", "--experimental-strip-types", "--no-warnings", "relayer/src/main.ts"]
